### ISSUE TITLE
CEF format issue

### ISSUE THREAD

**Issue by txasman** [O365Squad/O365-Squatting#1]
Hi,

No matter what python version, linux distribution, I get this errors:

$# python2 o365squatting.py
Traceback (most recent call last):
  File "o365squatting.py", line 3, in <module>
    import pycef
  File "/usr/local/lib/python2.7/dist-packages/pycef/__init__.py", line 43
    logger.warning(f'Blank field(s) in CEF header. Is it valid CEF format?')
                                                                          ^
SyntaxError: invalid syntax

python3:

$#python3 o365squatting.py -h
  File "o365squatting.py", line 187
    print e
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?

I've tried modifying the related lines, but no luck...

Thx!

**Comment by O365Squad** [comment]
Hi txasman,

Thank you for contacting us for this, the current version of pycef only works on python3 due to the use of F-strings.

That being said, you have 2 options:
- If you are using Python2.X, edit the line of pycef's core file init.py (just the file and line that your error message says) to remove the cast to F-string, just remove the "f" character prior the string, so the line should look like this:

logger.warning('Blank field(s) in CEF header. Is it valid CEF format?')   

- If you are using Python3.X we are going to pull a python3 version of O365 Squatting so you can use it with pycef with no issues from scratch. Just keep in mind that if you have both python versions installed in your system yo need to verify you are installing pycef in python3 instead (by using pip3 install pycef).

Please let us know if it works.

Thank you.

**Comment by sreemanshanker** [comment]
Hi !
Using python 2.7.18rc1 and have done the change as pointed above.
However getting the below error now:
minty:~/O365-Squatting$ python o365squatting.py -d defcon.org
Traceback (most recent call last):
  File "o365squatting.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by sreemanshanker** [comment]
that works !

**Comment by txasman** [comment]
Thanks! And I'm very sorry for the delay answering back.... My comment wasn't sent at the time :(
