### ISSUE TITLE
OnHold domains do not show up as "existing" in the list.

### ISSUE THREAD

**Issue by Absoblogginlutely** [O365Squad/O365-Squatting#2]
Great tool - thought I would run it against our domain and found some good phishing candidates. One of the domains showed up as false in all attributes , but the domain is actually registered and has a whois record, but the domain is currently in a onhold status. As it's on-hold, the domain does not return any dns records and so the domain shows false for all records.

Technically the domain does exist so could pose a phishing threat at a later date once the owner pays the registration fee's. However, in it's current status it is safe.

Wondering if it's worth doing a whois lookup on the domain in this script as well as DNS records?

**Comment by O365Squad** [comment]
Hi Absoblogginlutely,

Thank you for contacting us in this regard. We were studying your case and we consider it is a good improvement for our tool to catch OnHold domains. 

We need some test cases to add this feature. If you can share any domain will speed up the process, but is not mandatory.

Once again, thank you for your suggestion, we will keep you updated!

**Comment by Absoblogginlutely** [comment]
The squatted domain is easyLt.com for the actual domain of easyit.com. A very sneaky typo for our domain when consider ours is typically typed EasyIT.com

**Comment by Absoblogginlutely** [comment]
A similar (real life scenario) also occurred where someone purchased the .org equivalent domain for the live .com and then sent phishing emails. Those ended up compromising the domain (before they were our customer) and then they tried again about 8 months later. The second time the client picked up the bad domain (yay phish training and experience!) and notified us. 

This domain attack is not picked up through the typo tool as it's purely looking for character swaps rather than .com/org/co.uk 
Would this be considered a relevant feature or a different tool due to the domains not being the same?

**Comment by O365Squad** [comment]
Hi Absoblogginlutely,

thank you for examples and elaborated explanation, we will take this case as a reference for new ways to verify existing domains in our tool for a new coming version.

TLD checking like .com/org/co.uk was not considered at first as it was not compatible with domain creation in O365, but according to another issue we have, second-level domains are not processed by our tool (i.e.: .net.uk ), but they could also be used to create domains in O365. Because of this, we will push this in the new version too.

Once again, thank you for your help with this, as it will improve our tool and help other teams to find more domains :)

Best Regards.
